import type { Metadata } from "next";
import { Forum, Arizonia } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";

const forum = Forum({ 
  subsets: ['latin'],
  weight: '400',
  variable: '--font-forum',
});

const arizonia = Arizonia({ 
  subsets: ['latin'],
  weight: '400',
  variable: '--font-arizonia',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${forum.variable} ${arizonia.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
